/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.lab2.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.rm2pt.sample.lab2.ide.contentassist.antlr.internal.InternalDslParser;
import org.rm2pt.sample.lab2.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup_3(), "rule__Class__Group_3__0");
			builder.put(grammarAccess.getClassAccess().getGroup_4(), "rule__Class__Group_4__0");
			builder.put(grammarAccess.getClassAccess().getGroup_5(), "rule__Class__Group_5__0");
			builder.put(grammarAccess.getClassAccess().getGroup_6(), "rule__Class__Group_6__0");
			builder.put(grammarAccess.getClassAccess().getGroup_6_3(), "rule__Class__Group_6_3__0");
			builder.put(grammarAccess.getClassAccess().getGroup_7(), "rule__Class__Group_7__0");
			builder.put(grammarAccess.getClassAccess().getGroup_7_3(), "rule__Class__Group_7_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup(), "rule__Teacher__Group__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_3(), "rule__Teacher__Group_3__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_4(), "rule__Teacher__Group_4__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_8(), "rule__Teacher__Group_8__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_10(), "rule__Teacher__Group_10__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_10_3(), "rule__Teacher__Group_10_3__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_11(), "rule__Teacher__Group_11__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_11_3(), "rule__Teacher__Group_11_3__0");
			builder.put(grammarAccess.getStudentAccess().getGroup(), "rule__Student__Group__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_3(), "rule__Student__Group_3__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_4(), "rule__Student__Group_4__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_7(), "rule__Student__Group_7__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_7_3(), "rule__Student__Group_7_3__0");
			builder.put(grammarAccess.getCourseAccess().getGroup(), "rule__Course__Group__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_4(), "rule__Course__Group_4__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_5(), "rule__Course__Group_5__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_6(), "rule__Course__Group_6__0");
			builder.put(grammarAccess.getReportCardAccess().getGroup(), "rule__ReportCard__Group__0");
			builder.put(grammarAccess.getReportCardAccess().getGroup_3(), "rule__ReportCard__Group_3__0");
			builder.put(grammarAccess.getReportCardAccess().getGroup_4(), "rule__ReportCard__Group_4__0");
			builder.put(grammarAccess.getReportCardAccess().getGroup_5(), "rule__ReportCard__Group_5__0");
			builder.put(grammarAccess.getReportCardAccess().getGroup_6(), "rule__ReportCard__Group_6__0");
			builder.put(grammarAccess.getReportCardAccess().getGroup_7(), "rule__ReportCard__Group_7__0");
			builder.put(grammarAccess.getSubmitedPaperAccess().getGroup(), "rule__SubmitedPaper__Group__0");
			builder.put(grammarAccess.getSubmitedPaperAccess().getGroup_5(), "rule__SubmitedPaper__Group_5__0");
			builder.put(grammarAccess.getSubmitedPaperAccess().getGroup_6(), "rule__SubmitedPaper__Group_6__0");
			builder.put(grammarAccess.getSubmitedPaperAccess().getGroup_7(), "rule__SubmitedPaper__Group_7__0");
			builder.put(grammarAccess.getSubmitedPaperAccess().getGroup_8(), "rule__SubmitedPaper__Group_8__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup(), "rule__ExamPaper__Group__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_5(), "rule__ExamPaper__Group_5__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_6(), "rule__ExamPaper__Group_6__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_7(), "rule__ExamPaper__Group_7__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_8(), "rule__ExamPaper__Group_8__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_9(), "rule__ExamPaper__Group_9__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_10(), "rule__ExamPaper__Group_10__0");
			builder.put(grammarAccess.getExamPaperAccess().getGroup_10_3(), "rule__ExamPaper__Group_10_3__0");
			builder.put(grammarAccess.getClassAccess().getIdAssignment_3_1(), "rule__Class__IdAssignment_3_1");
			builder.put(grammarAccess.getClassAccess().getStudentnumAssignment_4_1(), "rule__Class__StudentnumAssignment_4_1");
			builder.put(grammarAccess.getClassAccess().getGradeAssignment_5_1(), "rule__Class__GradeAssignment_5_1");
			builder.put(grammarAccess.getClassAccess().getTeacherAssignment_6_2(), "rule__Class__TeacherAssignment_6_2");
			builder.put(grammarAccess.getClassAccess().getTeacherAssignment_6_3_1(), "rule__Class__TeacherAssignment_6_3_1");
			builder.put(grammarAccess.getClassAccess().getStudentAssignment_7_2(), "rule__Class__StudentAssignment_7_2");
			builder.put(grammarAccess.getClassAccess().getStudentAssignment_7_3_1(), "rule__Class__StudentAssignment_7_3_1");
			builder.put(grammarAccess.getTeacherAccess().getNameAssignment_1(), "rule__Teacher__NameAssignment_1");
			builder.put(grammarAccess.getTeacherAccess().getIdAssignment_3_1(), "rule__Teacher__IdAssignment_3_1");
			builder.put(grammarAccess.getTeacherAccess().getClassidAssignment_4_1(), "rule__Teacher__ClassidAssignment_4_1");
			builder.put(grammarAccess.getTeacherAccess().getCorrectAssignment_7(), "rule__Teacher__CorrectAssignment_7");
			builder.put(grammarAccess.getTeacherAccess().getCorrectAssignment_8_1(), "rule__Teacher__CorrectAssignment_8_1");
			builder.put(grammarAccess.getTeacherAccess().getTeachingAssignment_10_2(), "rule__Teacher__TeachingAssignment_10_2");
			builder.put(grammarAccess.getTeacherAccess().getTeachingAssignment_10_3_1(), "rule__Teacher__TeachingAssignment_10_3_1");
			builder.put(grammarAccess.getTeacherAccess().getInputAssignment_11_2(), "rule__Teacher__InputAssignment_11_2");
			builder.put(grammarAccess.getTeacherAccess().getInputAssignment_11_3_1(), "rule__Teacher__InputAssignment_11_3_1");
			builder.put(grammarAccess.getStudentAccess().getNameAssignment_1(), "rule__Student__NameAssignment_1");
			builder.put(grammarAccess.getStudentAccess().getIdAssignment_3_1(), "rule__Student__IdAssignment_3_1");
			builder.put(grammarAccess.getStudentAccess().getClassidAssignment_4_1(), "rule__Student__ClassidAssignment_4_1");
			builder.put(grammarAccess.getStudentAccess().getHaveAssignment_6(), "rule__Student__HaveAssignment_6");
			builder.put(grammarAccess.getStudentAccess().getAnswerAssignment_7_2(), "rule__Student__AnswerAssignment_7_2");
			builder.put(grammarAccess.getStudentAccess().getAnswerAssignment_7_3_1(), "rule__Student__AnswerAssignment_7_3_1");
			builder.put(grammarAccess.getCourseAccess().getNameAssignment_2(), "rule__Course__NameAssignment_2");
			builder.put(grammarAccess.getCourseAccess().getIdAssignment_4_1(), "rule__Course__IdAssignment_4_1");
			builder.put(grammarAccess.getCourseAccess().getStunumAssignment_5_1(), "rule__Course__StunumAssignment_5_1");
			builder.put(grammarAccess.getCourseAccess().getMeanAssignment_6_1(), "rule__Course__MeanAssignment_6_1");
			builder.put(grammarAccess.getReportCardAccess().getIdAssignment_3_1(), "rule__ReportCard__IdAssignment_3_1");
			builder.put(grammarAccess.getReportCardAccess().getStuidAssignment_4_1(), "rule__ReportCard__StuidAssignment_4_1");
			builder.put(grammarAccess.getReportCardAccess().getStunameAssignment_5_1(), "rule__ReportCard__StunameAssignment_5_1");
			builder.put(grammarAccess.getReportCardAccess().getTotalscoreAssignment_6_1(), "rule__ReportCard__TotalscoreAssignment_6_1");
			builder.put(grammarAccess.getReportCardAccess().getRankAssignment_7_1(), "rule__ReportCard__RankAssignment_7_1");
			builder.put(grammarAccess.getSubmitedPaperAccess().getIfcorrectAssignment_1(), "rule__SubmitedPaper__IfcorrectAssignment_1");
			builder.put(grammarAccess.getSubmitedPaperAccess().getIfanswerAssignment_2(), "rule__SubmitedPaper__IfanswerAssignment_2");
			builder.put(grammarAccess.getSubmitedPaperAccess().getIdAssignment_5_1(), "rule__SubmitedPaper__IdAssignment_5_1");
			builder.put(grammarAccess.getSubmitedPaperAccess().getStuidAssignment_6_1(), "rule__SubmitedPaper__StuidAssignment_6_1");
			builder.put(grammarAccess.getSubmitedPaperAccess().getTeaidAssignment_7_1(), "rule__SubmitedPaper__TeaidAssignment_7_1");
			builder.put(grammarAccess.getSubmitedPaperAccess().getCourseidAssignment_8_1(), "rule__SubmitedPaper__CourseidAssignment_8_1");
			builder.put(grammarAccess.getExamPaperAccess().getIfanswerAssignment_1(), "rule__ExamPaper__IfanswerAssignment_1");
			builder.put(grammarAccess.getExamPaperAccess().getIfcorrectAssignment_2(), "rule__ExamPaper__IfcorrectAssignment_2");
			builder.put(grammarAccess.getExamPaperAccess().getIdAssignment_5_1(), "rule__ExamPaper__IdAssignment_5_1");
			builder.put(grammarAccess.getExamPaperAccess().getCourseidAssignment_6_1(), "rule__ExamPaper__CourseidAssignment_6_1");
			builder.put(grammarAccess.getExamPaperAccess().getTeaidAssignment_7_1(), "rule__ExamPaper__TeaidAssignment_7_1");
			builder.put(grammarAccess.getExamPaperAccess().getStuidAssignment_8_1(), "rule__ExamPaper__StuidAssignment_8_1");
			builder.put(grammarAccess.getExamPaperAccess().getScoreAssignment_9_1(), "rule__ExamPaper__ScoreAssignment_9_1");
			builder.put(grammarAccess.getExamPaperAccess().getSubmitAssignment_10_2(), "rule__ExamPaper__SubmitAssignment_10_2");
			builder.put(grammarAccess.getExamPaperAccess().getSubmitAssignment_10_3_1(), "rule__ExamPaper__SubmitAssignment_10_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
