/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.lab2.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStudentnumKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStudentnumAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStudentnumEIntParserRuleCall_4_1_0 = (RuleCall)cStudentnumAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cGradeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cGradeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cGradeEStringParserRuleCall_5_1_0 = (RuleCall)cGradeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTeacherKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTeacherAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTeacherTeacherParserRuleCall_6_2_0 = (RuleCall)cTeacherAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cTeacherAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cTeacherTeacherParserRuleCall_6_3_1_0 = (RuleCall)cTeacherAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cStudentKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cStudentAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cStudentStudentParserRuleCall_7_2_0 = (RuleCall)cStudentAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cStudentAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cStudentStudentParserRuleCall_7_3_1_0 = (RuleCall)cStudentAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Class returns Class:
		//    {Class}
		//    'Class'
		//    '{'
		//        ('id' id=EString)?
		//        ('studentnum' studentnum=EInt)?
		//        ('grade' grade=EString)?
		//        ('teacher' '{' teacher+=Teacher ( "," teacher+=Teacher)* '}' )?
		//        ('student' '{' student+=Student ( "," student+=Student)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Class}
		//'Class'
		//'{'
		//    ('id' id=EString)?
		//    ('studentnum' studentnum=EInt)?
		//    ('grade' grade=EString)?
		//    ('teacher' '{' teacher+=Teacher ( "," teacher+=Teacher)* '}' )?
		//    ('student' '{' student+=Student ( "," student+=Student)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Class}
		public Action getClassAction_0() { return cClassAction_0; }
		
		//'Class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
		
		//('studentnum' studentnum=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'studentnum'
		public Keyword getStudentnumKeyword_4_0() { return cStudentnumKeyword_4_0; }
		
		//studentnum=EInt
		public Assignment getStudentnumAssignment_4_1() { return cStudentnumAssignment_4_1; }
		
		//EInt
		public RuleCall getStudentnumEIntParserRuleCall_4_1_0() { return cStudentnumEIntParserRuleCall_4_1_0; }
		
		//('grade' grade=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'grade'
		public Keyword getGradeKeyword_5_0() { return cGradeKeyword_5_0; }
		
		//grade=EString
		public Assignment getGradeAssignment_5_1() { return cGradeAssignment_5_1; }
		
		//EString
		public RuleCall getGradeEStringParserRuleCall_5_1_0() { return cGradeEStringParserRuleCall_5_1_0; }
		
		//('teacher' '{' teacher+=Teacher ( "," teacher+=Teacher)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'teacher'
		public Keyword getTeacherKeyword_6_0() { return cTeacherKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//teacher+=Teacher
		public Assignment getTeacherAssignment_6_2() { return cTeacherAssignment_6_2; }
		
		//Teacher
		public RuleCall getTeacherTeacherParserRuleCall_6_2_0() { return cTeacherTeacherParserRuleCall_6_2_0; }
		
		//( "," teacher+=Teacher)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//teacher+=Teacher
		public Assignment getTeacherAssignment_6_3_1() { return cTeacherAssignment_6_3_1; }
		
		//Teacher
		public RuleCall getTeacherTeacherParserRuleCall_6_3_1_0() { return cTeacherTeacherParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('student' '{' student+=Student ( "," student+=Student)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'student'
		public Keyword getStudentKeyword_7_0() { return cStudentKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//student+=Student
		public Assignment getStudentAssignment_7_2() { return cStudentAssignment_7_2; }
		
		//Student
		public RuleCall getStudentStudentParserRuleCall_7_2_0() { return cStudentStudentParserRuleCall_7_2_0; }
		
		//( "," student+=Student)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//student+=Student
		public Assignment getStudentAssignment_7_3_1() { return cStudentAssignment_7_3_1; }
		
		//Student
		public RuleCall getStudentStudentParserRuleCall_7_3_1_0() { return cStudentStudentParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class TeacherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.Teacher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTeacherKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClassidKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cClassidAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cClassidEStringParserRuleCall_4_1_0 = (RuleCall)cClassidAssignment_4_1.eContents().get(0);
		private final Keyword cCorrectKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCorrectAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cCorrectSubmitedPaperCrossReference_7_0 = (CrossReference)cCorrectAssignment_7.eContents().get(0);
		private final RuleCall cCorrectSubmitedPaperEStringParserRuleCall_7_0_1 = (RuleCall)cCorrectSubmitedPaperCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cCorrectAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cCorrectSubmitedPaperCrossReference_8_1_0 = (CrossReference)cCorrectAssignment_8_1.eContents().get(0);
		private final RuleCall cCorrectSubmitedPaperEStringParserRuleCall_8_1_0_1 = (RuleCall)cCorrectSubmitedPaperCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cTeachingKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cTeachingAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cTeachingCourseParserRuleCall_10_2_0 = (RuleCall)cTeachingAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cTeachingAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cTeachingCourseParserRuleCall_10_3_1_0 = (RuleCall)cTeachingAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cInputKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cInputAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cInputReportCardParserRuleCall_11_2_0 = (RuleCall)cInputAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cInputAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cInputReportCardParserRuleCall_11_3_1_0 = (RuleCall)cInputAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Teacher returns Teacher:
		//    'Teacher'
		//    name=EString
		//    '{'
		//        ('id' id=EString)?
		//        ('classid' classid=EString)?
		//        'correct' '(' correct+=[SubmitedPaper|EString] ( "," correct+=[SubmitedPaper|EString])* ')'
		//        ('teaching' '{' teaching+=Course ( "," teaching+=Course)* '}' )?
		//        ('input' '{' input+=ReportCard ( "," input+=ReportCard)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Teacher'
		//name=EString
		//'{'
		//    ('id' id=EString)?
		//    ('classid' classid=EString)?
		//    'correct' '(' correct+=[SubmitedPaper|EString] ( "," correct+=[SubmitedPaper|EString])* ')'
		//    ('teaching' '{' teaching+=Course ( "," teaching+=Course)* '}' )?
		//    ('input' '{' input+=ReportCard ( "," input+=ReportCard)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Teacher'
		public Keyword getTeacherKeyword_0() { return cTeacherKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
		
		//('classid' classid=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'classid'
		public Keyword getClassidKeyword_4_0() { return cClassidKeyword_4_0; }
		
		//classid=EString
		public Assignment getClassidAssignment_4_1() { return cClassidAssignment_4_1; }
		
		//EString
		public RuleCall getClassidEStringParserRuleCall_4_1_0() { return cClassidEStringParserRuleCall_4_1_0; }
		
		//'correct'
		public Keyword getCorrectKeyword_5() { return cCorrectKeyword_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }
		
		//correct+=[SubmitedPaper|EString]
		public Assignment getCorrectAssignment_7() { return cCorrectAssignment_7; }
		
		//[SubmitedPaper|EString]
		public CrossReference getCorrectSubmitedPaperCrossReference_7_0() { return cCorrectSubmitedPaperCrossReference_7_0; }
		
		//EString
		public RuleCall getCorrectSubmitedPaperEStringParserRuleCall_7_0_1() { return cCorrectSubmitedPaperEStringParserRuleCall_7_0_1; }
		
		//( "," correct+=[SubmitedPaper|EString])*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//correct+=[SubmitedPaper|EString]
		public Assignment getCorrectAssignment_8_1() { return cCorrectAssignment_8_1; }
		
		//[SubmitedPaper|EString]
		public CrossReference getCorrectSubmitedPaperCrossReference_8_1_0() { return cCorrectSubmitedPaperCrossReference_8_1_0; }
		
		//EString
		public RuleCall getCorrectSubmitedPaperEStringParserRuleCall_8_1_0_1() { return cCorrectSubmitedPaperEStringParserRuleCall_8_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
		
		//('teaching' '{' teaching+=Course ( "," teaching+=Course)* '}' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'teaching'
		public Keyword getTeachingKeyword_10_0() { return cTeachingKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//teaching+=Course
		public Assignment getTeachingAssignment_10_2() { return cTeachingAssignment_10_2; }
		
		//Course
		public RuleCall getTeachingCourseParserRuleCall_10_2_0() { return cTeachingCourseParserRuleCall_10_2_0; }
		
		//( "," teaching+=Course)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//teaching+=Course
		public Assignment getTeachingAssignment_10_3_1() { return cTeachingAssignment_10_3_1; }
		
		//Course
		public RuleCall getTeachingCourseParserRuleCall_10_3_1_0() { return cTeachingCourseParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//('input' '{' input+=ReportCard ( "," input+=ReportCard)* '}' )?
		public Group getGroup_11() { return cGroup_11; }
		
		//'input'
		public Keyword getInputKeyword_11_0() { return cInputKeyword_11_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }
		
		//input+=ReportCard
		public Assignment getInputAssignment_11_2() { return cInputAssignment_11_2; }
		
		//ReportCard
		public RuleCall getInputReportCardParserRuleCall_11_2_0() { return cInputReportCardParserRuleCall_11_2_0; }
		
		//( "," input+=ReportCard)*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//input+=ReportCard
		public Assignment getInputAssignment_11_3_1() { return cInputAssignment_11_3_1; }
		
		//ReportCard
		public RuleCall getInputReportCardParserRuleCall_11_3_1_0() { return cInputReportCardParserRuleCall_11_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class StudentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.Student");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStudentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClassidKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cClassidAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cClassidEStringParserRuleCall_4_1_0 = (RuleCall)cClassidAssignment_4_1.eContents().get(0);
		private final Keyword cHaveKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cHaveAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cHaveReportCardCrossReference_6_0 = (CrossReference)cHaveAssignment_6.eContents().get(0);
		private final RuleCall cHaveReportCardEStringParserRuleCall_6_0_1 = (RuleCall)cHaveReportCardCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAnswerKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAnswerAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAnswerExamPaperParserRuleCall_7_2_0 = (RuleCall)cAnswerAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAnswerAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAnswerExamPaperParserRuleCall_7_3_1_0 = (RuleCall)cAnswerAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Student returns Student:
		//    'Student'
		//    name=EString
		//    '{'
		//        ('id' id=EString)?
		//        ('classid' classid=EString)?
		//        'have' have=[ReportCard|EString]
		//        ('answer' '{' answer+=ExamPaper ( "," answer+=ExamPaper)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Student'
		//name=EString
		//'{'
		//    ('id' id=EString)?
		//    ('classid' classid=EString)?
		//    'have' have=[ReportCard|EString]
		//    ('answer' '{' answer+=ExamPaper ( "," answer+=ExamPaper)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Student'
		public Keyword getStudentKeyword_0() { return cStudentKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
		
		//('classid' classid=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'classid'
		public Keyword getClassidKeyword_4_0() { return cClassidKeyword_4_0; }
		
		//classid=EString
		public Assignment getClassidAssignment_4_1() { return cClassidAssignment_4_1; }
		
		//EString
		public RuleCall getClassidEStringParserRuleCall_4_1_0() { return cClassidEStringParserRuleCall_4_1_0; }
		
		//'have'
		public Keyword getHaveKeyword_5() { return cHaveKeyword_5; }
		
		//have=[ReportCard|EString]
		public Assignment getHaveAssignment_6() { return cHaveAssignment_6; }
		
		//[ReportCard|EString]
		public CrossReference getHaveReportCardCrossReference_6_0() { return cHaveReportCardCrossReference_6_0; }
		
		//EString
		public RuleCall getHaveReportCardEStringParserRuleCall_6_0_1() { return cHaveReportCardEStringParserRuleCall_6_0_1; }
		
		//('answer' '{' answer+=ExamPaper ( "," answer+=ExamPaper)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'answer'
		public Keyword getAnswerKeyword_7_0() { return cAnswerKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//answer+=ExamPaper
		public Assignment getAnswerAssignment_7_2() { return cAnswerAssignment_7_2; }
		
		//ExamPaper
		public RuleCall getAnswerExamPaperParserRuleCall_7_2_0() { return cAnswerExamPaperParserRuleCall_7_2_0; }
		
		//( "," answer+=ExamPaper)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//answer+=ExamPaper
		public Assignment getAnswerAssignment_7_3_1() { return cAnswerAssignment_7_3_1; }
		
		//ExamPaper
		public RuleCall getAnswerExamPaperParserRuleCall_7_3_1_0() { return cAnswerExamPaperParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCourseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCourseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIdKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIdAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_4_1_0 = (RuleCall)cIdAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cStunumKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cStunumAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cStunumEIntParserRuleCall_5_1_0 = (RuleCall)cStunumAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMeanKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMeanAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMeanEFloatParserRuleCall_6_1_0 = (RuleCall)cMeanAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Course returns Course:
		//    {Course}
		//    'Course'
		//    name=EString
		//    '{'
		//        ('id' id=EString)?
		//        ('stunum' stunum=EInt)?
		//        ('mean' mean=EFloat)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Course}
		//'Course'
		//name=EString
		//'{'
		//    ('id' id=EString)?
		//    ('stunum' stunum=EInt)?
		//    ('mean' mean=EFloat)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Course}
		public Action getCourseAction_0() { return cCourseAction_0; }
		
		//'Course'
		public Keyword getCourseKeyword_1() { return cCourseKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('id' id=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'id'
		public Keyword getIdKeyword_4_0() { return cIdKeyword_4_0; }
		
		//id=EString
		public Assignment getIdAssignment_4_1() { return cIdAssignment_4_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_4_1_0() { return cIdEStringParserRuleCall_4_1_0; }
		
		//('stunum' stunum=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'stunum'
		public Keyword getStunumKeyword_5_0() { return cStunumKeyword_5_0; }
		
		//stunum=EInt
		public Assignment getStunumAssignment_5_1() { return cStunumAssignment_5_1; }
		
		//EInt
		public RuleCall getStunumEIntParserRuleCall_5_1_0() { return cStunumEIntParserRuleCall_5_1_0; }
		
		//('mean' mean=EFloat)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'mean'
		public Keyword getMeanKeyword_6_0() { return cMeanKeyword_6_0; }
		
		//mean=EFloat
		public Assignment getMeanAssignment_6_1() { return cMeanAssignment_6_1; }
		
		//EFloat
		public RuleCall getMeanEFloatParserRuleCall_6_1_0() { return cMeanEFloatParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ReportCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.ReportCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReportCardAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReportCardKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStuidKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStuidAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStuidEStringParserRuleCall_4_1_0 = (RuleCall)cStuidAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cStunameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cStunameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cStunameEStringParserRuleCall_5_1_0 = (RuleCall)cStunameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTotalscoreKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTotalscoreAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTotalscoreEFloatParserRuleCall_6_1_0 = (RuleCall)cTotalscoreAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRankKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRankAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cRankEIntParserRuleCall_7_1_0 = (RuleCall)cRankAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ReportCard returns ReportCard:
		//    {ReportCard}
		//    'ReportCard'
		//    '{'
		//        ('id' id=EString)?
		//        ('stuid' stuid=EString)?
		//        ('stuname' stuname=EString)?
		//        ('totalscore' totalscore=EFloat)?
		//        ('rank' rank=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ReportCard}
		//'ReportCard'
		//'{'
		//    ('id' id=EString)?
		//    ('stuid' stuid=EString)?
		//    ('stuname' stuname=EString)?
		//    ('totalscore' totalscore=EFloat)?
		//    ('rank' rank=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ReportCard}
		public Action getReportCardAction_0() { return cReportCardAction_0; }
		
		//'ReportCard'
		public Keyword getReportCardKeyword_1() { return cReportCardKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
		
		//('stuid' stuid=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'stuid'
		public Keyword getStuidKeyword_4_0() { return cStuidKeyword_4_0; }
		
		//stuid=EString
		public Assignment getStuidAssignment_4_1() { return cStuidAssignment_4_1; }
		
		//EString
		public RuleCall getStuidEStringParserRuleCall_4_1_0() { return cStuidEStringParserRuleCall_4_1_0; }
		
		//('stuname' stuname=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'stuname'
		public Keyword getStunameKeyword_5_0() { return cStunameKeyword_5_0; }
		
		//stuname=EString
		public Assignment getStunameAssignment_5_1() { return cStunameAssignment_5_1; }
		
		//EString
		public RuleCall getStunameEStringParserRuleCall_5_1_0() { return cStunameEStringParserRuleCall_5_1_0; }
		
		//('totalscore' totalscore=EFloat)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'totalscore'
		public Keyword getTotalscoreKeyword_6_0() { return cTotalscoreKeyword_6_0; }
		
		//totalscore=EFloat
		public Assignment getTotalscoreAssignment_6_1() { return cTotalscoreAssignment_6_1; }
		
		//EFloat
		public RuleCall getTotalscoreEFloatParserRuleCall_6_1_0() { return cTotalscoreEFloatParserRuleCall_6_1_0; }
		
		//('rank' rank=EInt)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'rank'
		public Keyword getRankKeyword_7_0() { return cRankKeyword_7_0; }
		
		//rank=EInt
		public Assignment getRankAssignment_7_1() { return cRankAssignment_7_1; }
		
		//EInt
		public RuleCall getRankEIntParserRuleCall_7_1_0() { return cRankEIntParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SubmitedPaperElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.SubmitedPaper");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSubmitedPaperAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIfcorrectAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIfcorrectIfcorrectKeyword_1_0 = (Keyword)cIfcorrectAssignment_1.eContents().get(0);
		private final Assignment cIfanswerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIfanswerIfanswerKeyword_2_0 = (Keyword)cIfanswerAssignment_2.eContents().get(0);
		private final Keyword cSubmitedPaperKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_5_1_0 = (RuleCall)cIdAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cStuidKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cStuidAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cStuidEStringParserRuleCall_6_1_0 = (RuleCall)cStuidAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTeaidKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTeaidAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTeaidEStringParserRuleCall_7_1_0 = (RuleCall)cTeaidAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCourseidKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cCourseidAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cCourseidEStringParserRuleCall_8_1_0 = (RuleCall)cCourseidAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//SubmitedPaper returns SubmitedPaper:
		//    {SubmitedPaper}
		//    (ifcorrect?='ifcorrect')?
		//    (ifanswer?='ifanswer')?
		//    'SubmitedPaper'
		//    '{'
		//        ('id' id=EString)?
		//        ('stuid' stuid=EString)?
		//        ('teaid' teaid=EString)?
		//        ('courseid' courseid=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SubmitedPaper}
		//(ifcorrect?='ifcorrect')?
		//(ifanswer?='ifanswer')?
		//'SubmitedPaper'
		//'{'
		//    ('id' id=EString)?
		//    ('stuid' stuid=EString)?
		//    ('teaid' teaid=EString)?
		//    ('courseid' courseid=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SubmitedPaper}
		public Action getSubmitedPaperAction_0() { return cSubmitedPaperAction_0; }
		
		//(ifcorrect?='ifcorrect')?
		public Assignment getIfcorrectAssignment_1() { return cIfcorrectAssignment_1; }
		
		//'ifcorrect'
		public Keyword getIfcorrectIfcorrectKeyword_1_0() { return cIfcorrectIfcorrectKeyword_1_0; }
		
		//(ifanswer?='ifanswer')?
		public Assignment getIfanswerAssignment_2() { return cIfanswerAssignment_2; }
		
		//'ifanswer'
		public Keyword getIfanswerIfanswerKeyword_2_0() { return cIfanswerIfanswerKeyword_2_0; }
		
		//'SubmitedPaper'
		public Keyword getSubmitedPaperKeyword_3() { return cSubmitedPaperKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('id' id=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'id'
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }
		
		//id=EString
		public Assignment getIdAssignment_5_1() { return cIdAssignment_5_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_5_1_0() { return cIdEStringParserRuleCall_5_1_0; }
		
		//('stuid' stuid=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'stuid'
		public Keyword getStuidKeyword_6_0() { return cStuidKeyword_6_0; }
		
		//stuid=EString
		public Assignment getStuidAssignment_6_1() { return cStuidAssignment_6_1; }
		
		//EString
		public RuleCall getStuidEStringParserRuleCall_6_1_0() { return cStuidEStringParserRuleCall_6_1_0; }
		
		//('teaid' teaid=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'teaid'
		public Keyword getTeaidKeyword_7_0() { return cTeaidKeyword_7_0; }
		
		//teaid=EString
		public Assignment getTeaidAssignment_7_1() { return cTeaidAssignment_7_1; }
		
		//EString
		public RuleCall getTeaidEStringParserRuleCall_7_1_0() { return cTeaidEStringParserRuleCall_7_1_0; }
		
		//('courseid' courseid=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'courseid'
		public Keyword getCourseidKeyword_8_0() { return cCourseidKeyword_8_0; }
		
		//courseid=EString
		public Assignment getCourseidAssignment_8_1() { return cCourseidAssignment_8_1; }
		
		//EString
		public RuleCall getCourseidEStringParserRuleCall_8_1_0() { return cCourseidEStringParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class ExamPaperElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.lab2.Dsl.ExamPaper");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExamPaperAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIfanswerAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIfanswerIfanswerKeyword_1_0 = (Keyword)cIfanswerAssignment_1.eContents().get(0);
		private final Assignment cIfcorrectAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIfcorrectIfcorrectKeyword_2_0 = (Keyword)cIfcorrectAssignment_2.eContents().get(0);
		private final Keyword cExamPaperKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_5_1_0 = (RuleCall)cIdAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCourseidKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCourseidAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCourseidEStringParserRuleCall_6_1_0 = (RuleCall)cCourseidAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTeaidKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTeaidAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTeaidEStringParserRuleCall_7_1_0 = (RuleCall)cTeaidAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cStuidKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cStuidAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cStuidEStringParserRuleCall_8_1_0 = (RuleCall)cStuidAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cScoreKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cScoreAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cScoreEFloatParserRuleCall_9_1_0 = (RuleCall)cScoreAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cSubmitKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cSubmitAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cSubmitSubmitedPaperParserRuleCall_10_2_0 = (RuleCall)cSubmitAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cSubmitAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cSubmitSubmitedPaperParserRuleCall_10_3_1_0 = (RuleCall)cSubmitAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//ExamPaper returns ExamPaper:
		//    {ExamPaper}
		//    (ifanswer?='ifanswer')?
		//    (ifcorrect?='ifcorrect')?
		//    'ExamPaper'
		//    '{'
		//        ('id' id=EString)?
		//        ('courseid' courseid=EString)?
		//        ('teaid' teaid=EString)?
		//        ('stuid' stuid=EString)?
		//        ('score' score=EFloat)?
		//        ('submit' '{' submit+=SubmitedPaper ( "," submit+=SubmitedPaper)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ExamPaper}
		//(ifanswer?='ifanswer')?
		//(ifcorrect?='ifcorrect')?
		//'ExamPaper'
		//'{'
		//    ('id' id=EString)?
		//    ('courseid' courseid=EString)?
		//    ('teaid' teaid=EString)?
		//    ('stuid' stuid=EString)?
		//    ('score' score=EFloat)?
		//    ('submit' '{' submit+=SubmitedPaper ( "," submit+=SubmitedPaper)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ExamPaper}
		public Action getExamPaperAction_0() { return cExamPaperAction_0; }
		
		//(ifanswer?='ifanswer')?
		public Assignment getIfanswerAssignment_1() { return cIfanswerAssignment_1; }
		
		//'ifanswer'
		public Keyword getIfanswerIfanswerKeyword_1_0() { return cIfanswerIfanswerKeyword_1_0; }
		
		//(ifcorrect?='ifcorrect')?
		public Assignment getIfcorrectAssignment_2() { return cIfcorrectAssignment_2; }
		
		//'ifcorrect'
		public Keyword getIfcorrectIfcorrectKeyword_2_0() { return cIfcorrectIfcorrectKeyword_2_0; }
		
		//'ExamPaper'
		public Keyword getExamPaperKeyword_3() { return cExamPaperKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('id' id=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'id'
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }
		
		//id=EString
		public Assignment getIdAssignment_5_1() { return cIdAssignment_5_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_5_1_0() { return cIdEStringParserRuleCall_5_1_0; }
		
		//('courseid' courseid=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'courseid'
		public Keyword getCourseidKeyword_6_0() { return cCourseidKeyword_6_0; }
		
		//courseid=EString
		public Assignment getCourseidAssignment_6_1() { return cCourseidAssignment_6_1; }
		
		//EString
		public RuleCall getCourseidEStringParserRuleCall_6_1_0() { return cCourseidEStringParserRuleCall_6_1_0; }
		
		//('teaid' teaid=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'teaid'
		public Keyword getTeaidKeyword_7_0() { return cTeaidKeyword_7_0; }
		
		//teaid=EString
		public Assignment getTeaidAssignment_7_1() { return cTeaidAssignment_7_1; }
		
		//EString
		public RuleCall getTeaidEStringParserRuleCall_7_1_0() { return cTeaidEStringParserRuleCall_7_1_0; }
		
		//('stuid' stuid=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'stuid'
		public Keyword getStuidKeyword_8_0() { return cStuidKeyword_8_0; }
		
		//stuid=EString
		public Assignment getStuidAssignment_8_1() { return cStuidAssignment_8_1; }
		
		//EString
		public RuleCall getStuidEStringParserRuleCall_8_1_0() { return cStuidEStringParserRuleCall_8_1_0; }
		
		//('score' score=EFloat)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'score'
		public Keyword getScoreKeyword_9_0() { return cScoreKeyword_9_0; }
		
		//score=EFloat
		public Assignment getScoreAssignment_9_1() { return cScoreAssignment_9_1; }
		
		//EFloat
		public RuleCall getScoreEFloatParserRuleCall_9_1_0() { return cScoreEFloatParserRuleCall_9_1_0; }
		
		//('submit' '{' submit+=SubmitedPaper ( "," submit+=SubmitedPaper)* '}' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'submit'
		public Keyword getSubmitKeyword_10_0() { return cSubmitKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//submit+=SubmitedPaper
		public Assignment getSubmitAssignment_10_2() { return cSubmitAssignment_10_2; }
		
		//SubmitedPaper
		public RuleCall getSubmitSubmitedPaperParserRuleCall_10_2_0() { return cSubmitSubmitedPaperParserRuleCall_10_2_0; }
		
		//( "," submit+=SubmitedPaper)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//submit+=SubmitedPaper
		public Assignment getSubmitAssignment_10_3_1() { return cSubmitAssignment_10_3_1; }
		
		//SubmitedPaper
		public RuleCall getSubmitSubmitedPaperParserRuleCall_10_3_1_0() { return cSubmitSubmitedPaperParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	
	
	private final ClassElements pClass;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final TeacherElements pTeacher;
	private final StudentElements pStudent;
	private final CourseElements pCourse;
	private final ReportCardElements pReportCard;
	private final SubmitedPaperElements pSubmitedPaper;
	private final EFloatElements pEFloat;
	private final EBooleanElements pEBoolean;
	private final ExamPaperElements pExamPaper;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pClass = new ClassElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pTeacher = new TeacherElements();
		this.pStudent = new StudentElements();
		this.pCourse = new CourseElements();
		this.pReportCard = new ReportCardElements();
		this.pSubmitedPaper = new SubmitedPaperElements();
		this.pEFloat = new EFloatElements();
		this.pEBoolean = new EBooleanElements();
		this.pExamPaper = new ExamPaperElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.rm2pt.sample.lab2.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Class returns Class:
	//    {Class}
	//    'Class'
	//    '{'
	//        ('id' id=EString)?
	//        ('studentnum' studentnum=EInt)?
	//        ('grade' grade=EString)?
	//        ('teacher' '{' teacher+=Teacher ( "," teacher+=Teacher)* '}' )?
	//        ('student' '{' student+=Student ( "," student+=Student)* '}' )?
	//    '}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Teacher returns Teacher:
	//    'Teacher'
	//    name=EString
	//    '{'
	//        ('id' id=EString)?
	//        ('classid' classid=EString)?
	//        'correct' '(' correct+=[SubmitedPaper|EString] ( "," correct+=[SubmitedPaper|EString])* ')'
	//        ('teaching' '{' teaching+=Course ( "," teaching+=Course)* '}' )?
	//        ('input' '{' input+=ReportCard ( "," input+=ReportCard)* '}' )?
	//    '}';
	public TeacherElements getTeacherAccess() {
		return pTeacher;
	}
	
	public ParserRule getTeacherRule() {
		return getTeacherAccess().getRule();
	}
	
	//Student returns Student:
	//    'Student'
	//    name=EString
	//    '{'
	//        ('id' id=EString)?
	//        ('classid' classid=EString)?
	//        'have' have=[ReportCard|EString]
	//        ('answer' '{' answer+=ExamPaper ( "," answer+=ExamPaper)* '}' )?
	//    '}';
	public StudentElements getStudentAccess() {
		return pStudent;
	}
	
	public ParserRule getStudentRule() {
		return getStudentAccess().getRule();
	}
	
	//Course returns Course:
	//    {Course}
	//    'Course'
	//    name=EString
	//    '{'
	//        ('id' id=EString)?
	//        ('stunum' stunum=EInt)?
	//        ('mean' mean=EFloat)?
	//    '}';
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//ReportCard returns ReportCard:
	//    {ReportCard}
	//    'ReportCard'
	//    '{'
	//        ('id' id=EString)?
	//        ('stuid' stuid=EString)?
	//        ('stuname' stuname=EString)?
	//        ('totalscore' totalscore=EFloat)?
	//        ('rank' rank=EInt)?
	//    '}';
	public ReportCardElements getReportCardAccess() {
		return pReportCard;
	}
	
	public ParserRule getReportCardRule() {
		return getReportCardAccess().getRule();
	}
	
	//SubmitedPaper returns SubmitedPaper:
	//    {SubmitedPaper}
	//    (ifcorrect?='ifcorrect')?
	//    (ifanswer?='ifanswer')?
	//    'SubmitedPaper'
	//    '{'
	//        ('id' id=EString)?
	//        ('stuid' stuid=EString)?
	//        ('teaid' teaid=EString)?
	//        ('courseid' courseid=EString)?
	//    '}';
	public SubmitedPaperElements getSubmitedPaperAccess() {
		return pSubmitedPaper;
	}
	
	public ParserRule getSubmitedPaperRule() {
		return getSubmitedPaperAccess().getRule();
	}
	
	//EFloat returns ecore::EFloat:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//ExamPaper returns ExamPaper:
	//    {ExamPaper}
	//    (ifanswer?='ifanswer')?
	//    (ifcorrect?='ifcorrect')?
	//    'ExamPaper'
	//    '{'
	//        ('id' id=EString)?
	//        ('courseid' courseid=EString)?
	//        ('teaid' teaid=EString)?
	//        ('stuid' stuid=EString)?
	//        ('score' score=EFloat)?
	//        ('submit' '{' submit+=SubmitedPaper ( "," submit+=SubmitedPaper)* '}' )?
	//    '}';
	public ExamPaperElements getExamPaperAccess() {
		return pExamPaper;
	}
	
	public ParserRule getExamPaperRule() {
		return getExamPaperAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
